### ISSUE TITLE
Does VeloView works on windows 10?

### ISSUE THREAD

**Issue by jasjuang** [Kitware/VeloView#12]
I am considering updating my 64 bit windows 7 to windows 10, but I need to have VeloView working as normal. Could someone let me know whether the Version 3.1.1 - Windows 64 Veloview as shown in  http://www.paraview.org/Wiki/VeloView works with windows 10?

**Comment by timthirion** [comment]
Hey @jasjuang, I just tested VeloView 3.1.1 on my Windows 10 64-bit system. Everything seems to work fine.

**Comment by jasjuang** [comment]
Thanks so much for letting me know!
