### ISSUE TITLE
Have built VeloView in Ubuntu 14.04, but how to use it?

### ISSUE THREAD

**Issue by drscopus** [Kitware/VeloView#19]
Hello, I have downloaded and built VeloView under Ubuntu 14.04 successfully. But I don't know how to launch and use it. I couldn't find where the executables are. 
Does anybody give me any clue? Thanks.

**Comment by bastienjacquet** [comment]
Hello,
If you correctly built VeloView, the executable is generated in ./bin/VeloView

Please note that you built using the SuperBuild, you need to explicitly activate the VeloView project with CMake.

Best,
Bastien Jacquet

**Comment by drscopus** [comment]
Thank  you ! I found it. For me , It is under the directory ~/Downloads/VeloView/build/veloview/src/veloview-build/bin
