### ISSUE TITLE
Ubuntu 16.04 CMake CMake/ParaViewModules.cmake:188

### ISSUE THREAD

**Issue by maym86** [Kitware/VeloView#20]
Getting this error when at [ 90%] Performing configure step for 'veloview':

```
CMake Error at CMake/ParaViewModules.cmake:163 (set_property):
  set_property could not find CACHE variable ENABLE_png.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  CMakeLists.txt:124 (process_dependencies)
```

And then this:

```
CMake Error at CMake/ParaViewModules.cmake:188 (include):
  include could not find load file:

    png
Call Stack (most recent call first):
  CMakeLists.txt:124 (process_dependencies)
```

This is how I am running cmake
`
cmake -DENABLE_veloview:BOOL=ON -DUSE_SYSTEM_python:BOOL=ON -DUSE_SYSTEM_boost:BOOL=ON -DUSE_SYSTEM_qt:BOOL=ON -DUSE_SYSTEM_pythonqt:BOOL=ON ../Superbuild`

libpng is installed
Thanks for any help you can provide
Mike

**Comment by timthirion** [comment]
Your build directory is inside the source directory? If so, that may cause problems. I recommend putting the build directory in a wholly separate place in your filesystem.

Second, I assume you've installed all the `apt-get` dependencies, as outlined in the Developer's Guide?

**Comment by wzijian** [comment]
I use this and it's OK:

cmake -DENABLE_veloview:BOOL=ON -DUSE_SYSTEM_python=ON ../veloview/Superbuild

**Comment by maym86** [comment]
Ended up using the install_veloview.sh script attached with a modifiled qt.cmake and CMakeLists.txt

[CMakeLists.txt](https://github.com/Kitware/VeloView/files/637994/CMakeLists.txt)
