### ISSUE TITLE
typos in Build Instructions

### ISSUE THREAD

**Issue by Chambana** [Kitware/VeloView#21]
from the build instructions:  
"mkdir build cd build cmake -DENABLE_veloview:BOOL=ON ../veloview/SuperBuild"

The git clone operation creates the case-sensitive directory:
 /VeloView/Superbuild (correct)
 /veloview/SuperBuild (incorrect)

**Comment by timthirion** [comment]
@Chambana In the spirit of open source, could you update the documentation RST and make a pull request? Please also add your notes from #22. I will review then update the PDF when it's merged.
