### ISSUE TITLE
Unable to start VeloView on Ubuntu 14.04.5 LTS (32 bits)

### ISSUE THREAD

**Issue by ssinfod** [Kitware/VeloView#29]
Hello, 

I was able to compile VeloView from the github repository by following the "VeloView Developer Guide"

However, I have the following error message when I try to run ./VeloView

rd@rd-VirtualBox:~/myfolder/VeloView/build/install/bin$ ./VeloView 
/home/rd/myfolder/VeloView/build/install/lib/veloview-3.1/VeloView: **error while loading shared libraries: libPythonQt.so: cannot open shared object file: No such file or directory**

However, I can see that the file **libPythonQt.so** was correctly built and located in this folder:
/home/rd/myfolder/VeloView/build/install/lib/libPythonQt.so

Here are the commands that I used to build VeloView on my Ubuntu 14.04.5 LTS (32 bits) clean machine.

```
sudo apt-get install -y git
sudo apt-get install -y cmake-curses-gui
sudo apt-get install -y build-essential
sudo apt-get install -y libboost-all-dev
sudo apt-get install -y libxt-dev
sudo apt-get install -y libbz2-dev
sudo apt-get install -y libqt4-dev
sudo apt-get install -y qt4-default
sudo apt-get install -y qt4-dev-tools
sudo apt-get install -y zlib1g-dev

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update
sudo apt-get install -y --reinstall cmake

sudo apt-get install -y flex
sudo apt-get install -y byacc
(note: I don't install libpcap-dev, I let the cmake build it.)

#When using Ubuntu 32 bits
sudo apt-get install -y gcc-multilib g++-multilib

#Configure and make
cd myfolder
git clone git://public.kitware.com/VeloView.git

cd VeloView
mkdir build
cd build
cmake -DENABLE_veloview:BOOL=ON -DUSE_SYSTEM_python:BOOL=ON -DUSE_SYSTEM_boost:BOOL=ON -DUSE_SYSTEM_qt:BOOL=ON -DUSE_SYSTEM_pythonqt:BOOL=ON ../Superbuild

export QT_SELECT=qt4
make -j4
sudo make install
sudo ldconfig -v

#Then I try to run it and I got the above error about libPythonQt.so:
cd install/bin
./VeloView

```

That is it.
Any idea how to resolve this issue ?
Thanks,

**Comment by trickyMan** [comment]
I wrote a shell:
`
#!/bin/sh

LP=~//build/install/lib  # which you shoule be replaced
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${LP}:${LP}/pandar-1.0:${LP}/paraview-4.3
export PYTHONPATH=${PYTHONPATH}:${LP}/paraview-4.3/site-packages:${LP}/pandar-1.0/site-packages:${LP}/paraview-4.3/site-packages/vtk/
cd ${LP}/../
./bin/Pandar
`
