### ISSUE TITLE
veloview 3.5 source code?

### ISSUE THREAD

**Issue by moskewcz** [Kitware/VeloView#33]
binaries of veloview 3.5 have been released for a little while now here:

https://www.paraview.org/Wiki/VeloView

but, it seems like the source code is nowhere to be found. anyone have any info/hints/advice?

**Comment by bastienjacquet** [comment]
Hello,
The code corresponding to VeloView 3.5 binaries will soon be released.
It just need some cleanup of the metadata for the commits not to interfere with github issues and merge requests.
Best regards,
Bastien Jacquet
VeloView Lead Developer

**Comment by moskewcz** [comment]
thanks for the update! i guess i'll close this if/when the 3.5 source show up ... ;)

**Comment by bastienjacquet** [comment]
Hello,
The code corresponding to VeloView 3.5.0 binaries has been released.
Best regards,
Bastien Jacquet
VeloView Lead Developer

**Comment by KrantiYadav** [comment]
Hi all,

I am new here for Veloview. I am looking for solution in python which will convert .pcap to .las.

Any help here?

Regards,
Kranti
