### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by ssy248** [Kitware/VeloView#42]
Error states:

-- PythonQt: Setting PythonQt_QT_VERSION to 4 because QT_QMAKE_EXECUTABLE is defined.
-- Found unsuitable Qt version "5.6.2" from /Users/sian/anaconda/bin/qmake
CMake Error at CMakeLists.txt:194 (message):
  error: Qt4 was not found on your system.  You probably need to set the
  QT_QMAKE_EXECUTABLE variable

**Comment by bastienjacquet** [comment]
As stated, VeloView need Qt4, and it only finds Qt5 on your system.
Please either install Qt4 and set QT_QMAKE_EXECUTABLE to Qt4's qmake, or tell the Superbuild to build Qt4.

**Comment by ssy248** [comment]
Ok, I did that.
