### ISSUE TITLE
Need help configuring CMake in RPi3

### ISSUE THREAD

**Issue by etanx** [Kitware/VeloView#63]
Following the Developer's guide, after installing dependencies and cloning the git on the Raspberry Pi I try to run:
`sudo ccmake <VeloView>/Superbuild`
But received:
`-bash: /Superbuild: Permission denied`
Seems like some simple step that I am missing!

I also could not find/identify the CMake configuration file where I am supposed to enable:
```
ENABLE_veloview=ON
USE_SYSTEM_boost=ON
USE_SYSTEM_python=ON
USE_SYSTEM_qt=ON
```

Thanks in advance for your help!

**Comment by vnn0804** [comment]
type following commaand
sudo ccmake VeloView/Superbuild
