### ISSUE TITLE
Using ParaView plugin

### ISSUE THREAD

**Issue by andre-nguyen** [Kitware/VeloView#64]
Hi there,

can anyone comment on how to use the plugin for paraview? 
1. I have the VelodyneHDL plugin loaded
![image](https://user-images.githubusercontent.com/6036318/49596120-973aaf80-f947-11e8-848d-916deec9d7bc.png)

2. I can see in sources the Velodyne HDL Reader option.

3. I add the Velodyne HDL Reader source into my pipeline and select my .pcap and .xml files and I clicked Apply.
![image](https://user-images.githubusercontent.com/6036318/49596190-c4875d80-f947-11e8-92c3-a0a02d3584bd.png)

However, when I click play both in the properties and on the main tool bar nothing happens.

Any ideas?

**Comment by bastienjacquet** [comment]
The ParaView loadable plugin is not actively supported anymore.
The upcoming VeloView 4.0 (June?) will resurrect it.
