### ISSUE TITLE
azimuth > 360?

### ISSUE THREAD

**Issue by chiyuan-goh** [Kitware/VeloView#7]
Is this correct?

<img width="1220" alt="screen shot 2015-12-05 at 11 35 16 pm" src="https://cloud.githubusercontent.com/assets/834508/11611285/7c158c90-9c00-11e5-83e4-4ecdf3c964be.png">

**Comment by timthirion** [comment]
Yes, that's correct. The azimuth is reported as an integer A in the range [0, 36000] where the actual degree value is A/100.0. The values in the screenshot above would be 143.89 degrees.
