### ISSUE TITLE
sensorInformationLabel and positionPacketInfoLabel not empty after close data

### ISSUE THREAD

**Issue by duncanyu8907** [Kitware/VeloView#75]
sensorInformationLabel and positionPacketInfoLabel at status bar still display information after close data
![github_LabelNotEmpty](https://user-images.githubusercontent.com/49302994/55611885-71b89800-57b9-11e9-8989-06df83eed4a2.PNG)

**Comment by PierreGuilbertF** [comment]
Hello,

Thanks for the pull request related to this issue

Regards,
Pierre Guilbert
