### ISSUE TITLE
calibration lidar and gps/imu

### ISSUE THREAD

**Issue by liuyf5231** [Kitware/VeloView#96]
hi,
 1.
 I want to calibrate lidar and gps(get the 6-DoF pose between lidar and gps). After reading the source code, I think the function `EstimateCalibrationFromPoses()`can do it, is it correct?  
  
 2. test data repo not found
  `fatal: repository 'https://github.com/Kitware/VeloView-TestData.git/' not found`

**Comment by pxc2017** [comment]
> hi,
> 
>  1.
> 
>  I want to calibrate lidar and gps(get the 6-DoF pose between lidar and gps). After reading the source code, I think the function `EstimateCalibrationFromPoses()`can do it, is it correct?  
> 
>   
> 
>  2. test data repo not found
> 
>   `fatal: repository 'https://github.com/Kitware/VeloView-TestData.git/' not found`

 hello i also look for some methods to calculate the transformation between gps and lidar.have you solved this problem?
