### ISSUE TITLE
Problems with Mac OS

### ISSUE THREAD

**Issue by mo-zahran** [Kitware/VeloView#99]
I tried to install the app on macOS Catalina 10.15.3, but it gives this error
```
“VeloView” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
```
<img width="420" alt="Screen Shot 2020-02-12 at 7 05 46 PM" src="https://user-images.githubusercontent.com/15180702/74358786-babe7d00-4dca-11ea-9a7d-6935ea153608.png">

**Comment by bastienjacquet** [comment]
As written in the message this ins not an error, but more of a warning.
You should be able to open it by authorizing the opening from unverified sources in your macOS settings (Most probably under the OS Security section).
Keep in mind we have not tested VeloView with macOS 10.15
